### ISSUE TITLE
[Feature Request] Scan a specific portion of the Hard Disk

### ISSUE THREAD

**Issue by swarup459** [TalAloni/HardDiskValidator#11]
Is it possible to add a feature to scan only a specific part of a Hard Disk (say 80% to 100% or, 400GB to 465GB or, Sector X to Sector Y)?

**Scenario 1**: I only want to scan a specific portion of a Hard Disk(say last 20%) and compare with the previous scan results.

**Scenario 2**: A big sized hard disk (say 2TB or more) takes too much time to scan with a USB 2.0 connection in one go. But one can check it by parts in 2 or 3 go without overloading the disk.

Thank you...

**Comment by TalAloni** [comment]
I think it's one of those features that are useful for 1% of users and confuse the other 99%. so no. just scan the entire drive.

**Comment by swarup459** [comment]
Never mind. After Googling some time I have found that [HD Tune](https://www.hdtune.com/) has that feature of checking a specific portion of a Hard Disk. I am attching a screenshot of it hoping it will help 1% of those users who need the feature. Thank you again.

![HD_Tune](https://user-images.githubusercontent.com/60686348/112722629-b4d51e00-8f30-11eb-95a3-3f2bb98a2613.png)

**Comment by vecerap** [comment]
@TalAloni 
> I think it's one of those features that are useful for 1% of users and confuse the other 99%. so no. just scan the entire drive.

I think the 99% will be still confused which scanning mode to use, including myself and having to read the readme of this repository. Nonetheless the target audience which will probably use this program will be smart enough to understand what two numbers mean. 

Would be nice if modes would have tooltip description what does the mode do after mouse hover.

Scenario two from @swarup459 is most common case even for not so big drives like 3TB which still took about 2 days to finish on USB 3 speeds...

For me I do not deny that I might make the requested addition someday, but would like to know if my contribution will be accepted and my effort would not be useless.

Thank you.

**Comment by TalAloni** [comment]
@vecerap Asked and answered. The program is open source so you could fork it and provide whatever features you find useful.

**Comment by vecerap** [comment]
> @vecerap Asked and answered. The program is open source so you could fork it and provide whatever features you find useful.

I agree but the features aways depends whether the author of the project will accept them. And I saw you made denial of the request.

**Comment by TalAloni** [comment]
I suggested that you become the author of the fork and decide what to accept.
