### ISSUE TITLE
SSD's

### ISSUE THREAD

**Issue by boydfields** [TalAloni/HardDiskValidator#12]
Is this suitable for SSD's?  For example, to check for bad cells?  As I understand, SSD's have an internal system whereby they keep changing which cells are being used in order to perform wear levelling.  However, if a cell reports its address to be xyz, surely a program can read from it and see if the data is corrupt or not?

Sorry if I'm asking a stupid / invalid question.

**Comment by TalAloni** [comment]
Hi,
Yes, it is suitable for SSDs, although the chances of an SSD corrupting data are quite slim.
