### ISSUE TITLE
System.IO.IOException: 'Unable to retrieve device number'

### ISSUE THREAD

**Issue by Amplificator** [TalAloni/HardDiskValidator#14]
Hi.

I'm attempting to recreate this project, but when I run the line:
`List<PhysicalDisk> disks = PhysicalDiskHelper.GetPhysicalDisks();`

I get this error:
`System.IO.IOException: 'Unable to retrieve device number'`

Any solution to this?

**Comment by TalAloni** [comment]
Are you running as administrator?

**Comment by Amplificator** [comment]
Oh, somehow I missed running it as admin - problem solved, thank you :)
