### ISSUE TITLE
"Current pending sector count" repairable with HDV?

### ISSUE THREAD

**Issue by bsto** [TalAloni/HardDiskValidator#3]
In the past I got several times a SMART warning "Current pending sector count" shown e.g. in "CrystalDiskInfo" tool.

In order to repair it I had to backup the whole partition to an external hard disk.
Then reformat the whole partition (in order to replace the bad sector(s) by a reserve sector(s).
And finaly re-copy all the stuff from external hard disk.

This procedure is very unhandy and tedious.

When I look at the hard disk validor menu I can see a
"Read + Write Damaged + Read" entry.

Can I repair/replace easily the bad sector(s) with this test?
Read: avoid the procedure described above?

**Comment by TalAloni** [comment]
Yes, the purpose of that test is to only generate writes for those bad sectors, and let the disk handle it as it sees fit. if the sector is unreadable that the data on that sector is lost, the rest of the data is preserved.
