### ISSUE TITLE
While using the program after a while disk seems to get disconnected?

### ISSUE THREAD

**Issue by kemal1132** [TalAloni/HardDiskValidator#5]
After a power failure, I noticed that my 3TB hard disk has some bad sectors(some programs consistently freeze). As I don't know if the platter was damaged I decided to run the program read-write-verify-restore overnight. 
here is the log: https://pastebin.com/Kwixcw9f
GUI was saying everything inaccessible was damaged, but I know that isn't true as I can use most programs on the disk without any problems. This seems to be disk just sleeping after a while, though I don't know why. It is consistent as same thing happened once more when I tried it again.

**Comment by TalAloni** [comment]
ERROR_DEV_NOT_EXIST means that the disk disconnected itself (definitely not sleeping), it's likely that the disk is dying, I suggest backing up everything you can ASAP.
