### ISSUE TITLE
Build error because of missing files

### ISSUE THREAD

**Issue by efvb** [TalAloni/HardDiskValidator#6]
The code for this 2 projects are missing in the solution.

The referenced project '..\..\DynamicDiskPartitioner\DiskAccessLibrary\DiskAccessLibrary.csproj' does not exist.

The referenced project '..\..\DynamicDiskPartitioner\Utilities\Utilities.csproj' does not exist.

**Comment by Smurf-IV** [comment]
I found these by loading another project from https://github.com/TalAloni/DynamicDiskPartitioner
