### ISSUE TITLE
source code is incomplete - libraries are missing

### ISSUE THREAD

**Issue by nzain** [TalAloni/HardDiskValidator#8]
Just downloaded the source code - but the libraries `Utilities` and `DiskAccessLibrary` are missing. Thus, it doesn't compile.

Could you commit those libraries or include references where to get them?

**Comment by TalAloni** [comment]
Hi,
They are [available here](https://github.com/TalAloni/DynamicDiskPartitioner)
I'll try to replace the reference with a NuGet reference when I'll have time,

**Comment by TalAloni** [comment]
Done.
