### ISSUE TITLE
What exactly does "IO Error" mean?

### ISSUE THREAD

**Issue by besweeet** [TalAloni/HardDiskValidator#9]
Currently doing a read test and a few blocks already displayed an "IO error" as shown in this screenshot:
![Screenshot](https://i.imgur.com/PDp3xTK.png)

What exactly does this mean? Was it an issue with the actual drive and / or possibly with the USB 3.0 enclosure that I'm using?

**Comment by TalAloni** [comment]
It means a command was issued to the drive and the result was not as expected (error was returned), it can be due to a poor connection or a drive going bad.

**Comment by besweeet** [comment]
> It means a command was issued to the drive and the result was not as expected (error was returned), it can be due to a poor connection or a drive going bad.

Gotcha. Crystal Disk Info is reporting abnormal "current pending sector count" and some of the files come back as corrupt. Sounds like an old drive is simply going bad.
